FROM node:12.18.4

WORKDIR /app

COPY ./frontend/package.json .
COPY ./frontend/yarn.lock .

RUN yarn install

COPY ./frontend .

COPY ./.env .

FROM nginx

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf