version: '3.7'

networks:
  database:
  frontend:

services:
  database:
    image: mongo:4.4
    container_name: oyster-test-database-prod
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    networks:
      database:
        aliases:
          - database
  backend:
    build:
      dockerfile: ./backend/Dockerfile.prod
    container_name: oyster-test-backend-prod
    working_dir: /app
    depends_on:
      - database
    ports:
      - 3000:3000
    networks:
      database:
      frontend:
        aliases:
          - backend
    command: ['yarn', 'start:prod']
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile.prod
    container_name: oyster-test-frontend-prod
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      frontend:
        aliases:
          - frontend
    command: ['tail', '-f', '/dev/null']
