version: '3.7'

networks:
  database:

volumes:
  mongo_data:

services:
  database:
    image: mongo:4.4
    container_name: oyster-test-database
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - mongo_data:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    networks:
      database:
        aliases:
          - database
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: oyster-test-backend
    working_dir: /app
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      database:
    command: ['yarn', 'start:dev']
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: oyster-test-frontend
    working_dir: /app
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ['yarn', 'start']
